import type { Beracha } from "./types";

// Opening common to every beracha that uses Hashem's name.
const O_HE = "בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם";
const O_TR = "Baruch Atah Ado-nai Eloheinu Melech ha'olam";
const O_EN = "Blessed are You, Lord our God, King of the universe";

export const BERACHOT: Beracha[] = [
  {
    key: "hamotzi",
    nameEn: "HaMotzi",
    nameTranslit: "Hamotzi lechem min ha'aretz",
    hebrew: "הַמּוֹצִיא לֶחֶם מִן הָאָרֶץ",
    type: "rishona",
    hebrewFull: `${O_HE}, הַמּוֹצִיא לֶחֶם מִן הָאָרֶץ:`,
    translitFull: `${O_TR}, hamotzi lechem min ha'aretz.`,
    englishFull: `${O_EN}, who brings forth bread from the earth.`,
  },
  {
    key: "mezonot",
    nameEn: "Borei Minei Mezonot",
    nameTranslit: "Borei minei mezonot",
    hebrew: "בּוֹרֵא מִינֵי מְזוֹנוֹת",
    type: "rishona",
    hebrewFull: `${O_HE}, בּוֹרֵא מִינֵי מְזוֹנוֹת:`,
    translitFull: `${O_TR}, borei minei mezonot.`,
    englishFull: `${O_EN}, who creates varieties of nourishment.`,
  },
  {
    key: "hagafen",
    nameEn: "Borei Pri HaGafen",
    nameTranslit: "Borei peri hagafen",
    hebrew: "בּוֹרֵא פְּרִי הַגֶּפֶן",
    type: "rishona",
    hebrewFull: `${O_HE}, בּוֹרֵא פְּרִי הַגֶּפֶן:`,
    translitFull: `${O_TR}, borei peri hagafen.`,
    englishFull: `${O_EN}, who creates the fruit of the vine.`,
  },
  {
    key: "haetz",
    nameEn: "Borei Pri HaEtz",
    nameTranslit: "Borei peri ha'etz",
    hebrew: "בּוֹרֵא פְּרִי הָעֵץ",
    type: "rishona",
    hebrewFull: `${O_HE}, בּוֹרֵא פְּרִי הָעֵץ:`,
    translitFull: `${O_TR}, borei peri ha'etz.`,
    englishFull: `${O_EN}, who creates the fruit of the tree.`,
  },
  {
    key: "haadama",
    nameEn: "Borei Pri HaAdama",
    nameTranslit: "Borei peri ha'adama",
    hebrew: "בּוֹרֵא פְּרִי הָאֲדָמָה",
    type: "rishona",
    hebrewFull: `${O_HE}, בּוֹרֵא פְּרִי הָאֲדָמָה:`,
    translitFull: `${O_TR}, borei peri ha'adama.`,
    englishFull: `${O_EN}, who creates the fruit of the ground.`,
  },
  {
    key: "shehakol",
    nameEn: "Shehakol",
    nameTranslit: "Shehakol nihye bidvaro",
    hebrew: "שֶׁהַכֹּל נִהְיֶה בִּדְבָרוֹ",
    type: "rishona",
    hebrewFull: `${O_HE}, שֶׁהַכֹּל נִהְיֶה בִּדְבָרוֹ:`,
    translitFull: `${O_TR}, shehakol nihye bidvaro.`,
    englishFull: `${O_EN}, by whose word all things came to be.`,
  },
  {
    key: "nefashot",
    nameEn: "Borei Nefashot",
    nameTranslit: "Borei nefashot rabbot",
    hebrew: "בּוֹרֵא נְפָשׁוֹת רַבּוֹת",
    type: "acharona",
    hebrewFull: `${O_HE}, בּוֹרֵא נְפָשׁוֹת רַבּוֹת וְחֶסְרוֹנָן, עַל כָּל מַה שֶּׁבָּרָא לְהַחֲיוֹת בָּהֶם נֶפֶשׁ כָּל חָי. בָּרוּךְ חֵי הָעוֹלָמִים:`,
    translitFull: `${O_TR}, borei nefashot rabbot vechesronan, al kol mah shebara lehachayot bahem nefesh kol chai. Baruch chei ha'olamim.`,
    englishFull: `${O_EN}, Creator of many living beings and their needs, for all that You created with which to sustain the life of every living being. Blessed is He who is the Life of the worlds.`,
  },
  {
    key: "almichya",
    nameEn: "Al HaMichya",
    nameTranslit: "Al hamichya v'al hakalkala",
    hebrew: "עַל הַמִּחְיָה וְעַל הַכַּלְכָּלָה",
    type: "acharona",
    hebrewFull: "עַל הַמִּחְיָה וְעַל הַכַּלְכָּלָה… (the full me'ein shalosh)",
    translitFull: "Al hamichya v'al hakalkala… (full text)",
    englishFull: "The full me'ein shalosh after-blessing for the five grains.",
    tefilaSlug: "al-hamichya",
  },
  {
    key: "algefen",
    nameEn: "Al HaGefen",
    nameTranslit: "Al hagefen v'al peri hagefen",
    hebrew: "עַל הַגֶּפֶן וְעַל פְּרִי הַגֶּפֶן",
    type: "acharona",
    hebrewFull: "עַל הַגֶּפֶן וְעַל פְּרִי הַגֶּפֶן… (the full me'ein shalosh)",
    translitFull: "Al hagefen v'al peri hagefen… (full text)",
    englishFull: "The full me'ein shalosh after-blessing for wine and grape juice.",
    tefilaSlug: "al-hagefen",
  },
  {
    key: "haetz_acharona",
    nameEn: "Al HaEtz",
    nameTranslit: "Al ha'etz v'al peri ha'etz",
    hebrew: "עַל הָעֵץ וְעַל פְּרִי הָעֵץ",
    type: "acharona",
    hebrewFull: "עַל הָעֵץ וְעַל פְּרִי הָעֵץ… (the full me'ein shalosh)",
    translitFull: "Al ha'etz v'al peri ha'etz… (full text)",
    englishFull: "The full me'ein shalosh after-blessing for the five fruits.",
    tefilaSlug: "al-haetz",
  },
  {
    key: "birkat_hamazon",
    nameEn: "Birkat HaMazon",
    nameTranslit: "Birkat hamazon",
    hebrew: "בִּרְכַּת הַמָּזוֹן",
    type: "acharona",
    hebrewFull: "בִּרְכַּת הַמָּזוֹן… (the full Grace after Meals)",
    translitFull: "Birkat hamazon… (full text)",
    englishFull: "The full Grace after Meals, said after a meal with bread.",
    tefilaSlug: "birkat-hamazon",
  },
];

export const berachaKeys = BERACHOT.map((b) => b.key);
export const berachaByKey = new Map(BERACHOT.map((b) => [b.key, b]));
